### ISSUE TITLE
Compare and document resource usage (CPU & memory) after engine updates

### ISSUE THREAD

**Issue by pstadermann** [GDATASoftwareAG/vaas-helm#4]
Acceptance criteria:

* For our test set, compare old and new
	* Runtime
	* Max memory usage

**Comment by lennartdohmann** [comment]
### Summary

Required memory per node: 1,5 GB + 512 MB / CPU core

Performance for 2 x 4 Core Intel Skylake node:

- Files / s: 53.7
- MB / s: 55.2 

### Benchmarks

- 2 Nodes
- 4 cores (8 threads)
- Intel Skylake
- 12 GB RAM

### Ressources used under full load

- CPUs: 100% of node
- Memory: 
  - per node 4 GB (Scanner)
  - Once 0,5 GB (Gateway + Redis)

### Peak performance

- Number of files: 27297
- Total size: 28065M
- Average file size: 1.03M
- Files / s: 53.7
- MB / s: 55.2
