### ISSUE TITLE
Allow Users to provide ImagePullSecrets from outside of the values

### ISSUE THREAD

**Issue by jdftapi** [GDATASoftwareAG/vaas-helm#57]
We are managing our secrets using external tooling and would like the helm chart to accept secret references instead of the inline `imagePullSecret` in the `values.yaml` file.

Currently, the `helm.sh` forces us to use the inline secret.

**Comment by unglaublicherdude** [comment]
Hi, there was already the possibility to provide your own secrets, but it was buggy. We had a bug in the chart, that lead to it always wanting an `global.secret.dockerjsonconfig` regardless of you having configured an entry in  `global.imagepullsecrets`.

In the new version you can configure just one of the options or both. I wait for the review of my workmates before merging the fix.
